import { GetStaticProps, GetStaticPaths, InferGetStaticPropsType } from "next/types";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export interface BLOG {
    id: number;
    categories: string[];
    date: string;
    description: string;
    slug: string;
    tags: string[];
    title: string;
    contents: string;
}

const fs = require('fs');
const fm = require('front-matter');

const blog = ({ blog, contentsHtml }: InferGetStaticPropsType<typeof getStaticProps>) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/" />
            </Head>

            <main className={styles.main}>
                <table>
                    <tr>
                        <th>카테고리</th>
                        <th>제목</th>
                        <th>작성일자</th>
                        <th>태그</th>
                    </tr>
                    <tr>
                        <td>{blog.categories}</td>
                        <td>{blog.title}</td>
                        <td>{blog.date}</td>
                        <td>{blog.tags}</td>
                    </tr>
                    <tr>
                        <td colSpan={4} dangerouslySetInnerHTML={{ __html: contentsHtml }}>
                        </td>
                    </tr>
                </table>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    );
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
    const { id } = params as any;

    const data = await fs.readFileSync(process.cwd().concat(`/__posts/${id}.md`), 'utf-8');

    const parseResult = fm(data);
    const blog = parseResult.attributes;
    const contentsHtml = parseResult.body;

    return {
        props: {
            blog,
            contentsHtml,
        },
    };
};

export const getStaticPaths: GetStaticPaths = async () => {
    const dir = process.cwd().concat('/__posts');

    const files: string[] = await fs.readdirSync(dir);

    const paths = files.map((fileName: string) => {
        const fileNameNoExt = fileName.replace(/\.md$/, '');

        return { params: { id: fileNameNoExt } }
    });

    return { paths, fallback: false };
};

export default blog;